### ISSUE TITLE
Error when building faiss index.

### ISSUE THREAD

**Issue by SefaZeng** [zhengxxn/adaptive-knn-mt#1]
I try to use a data whose dstore_size is 750101549 to build datastore and faiss index. It's ok build to datastore but it raise error when build the faiss index. 
Is there any way to solve this problem?
The scripts is
```
#/bin/bash
work_dir=/data/root/knn
PROJECT_PATH=$work_dir/adaptive-knn-mt-main
SIGNATURE=data
DSTORE_PATH=$xianf_dir/datastore/$SIGNATURE
DSTORE_SIZE=750101549
export PYTHONPATH=$PROJECT_PATH:$PYTHONPATH                                              
   
CUDA_VISIBLE_DEVICES=0 python $PROJECT_PATH/train_datastore_gpu.py \
  --dstore_mmap $DSTORE_PATH \
  --dstore_size $DSTORE_SIZE \
  --dstore-fp16 \
  --faiss_index ${DSTORE_PATH}/knn_index \
  --ncentroids 3072 \
  --probe 32 \
  --dimension 1024
```
```
Traceback (most recent call last):
  File "/data/root/knn/adaptive-knn-mt-main/train_datastore_gpu.py", line 113, in <module>
    gpu_index.add_with_ids(to_add.astype(np.float32), np.arange(start, end))
  File "/usr/local/python3/lib/python3.6/site-packages/faiss/__init__.py", line 214, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "/usr/local/python3/lib/python3.6/site-packages/faiss/swigfaiss.py", line 5756, in add_with_ids
    return _swigfaiss.GpuIndex_add_with_ids(self, n, x, ids)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type IVFLists dev 0 space Device stream 0x2d6cbc0 size 8388608 bytes (cudaMalloc error out of memory [2])
```

**Comment by zhengxxn** [comment]
It seems that the datastore is too big to put into GPU, maybe you can try building index with CPU ( use train_datastore.py, but this will slow the retrieval speed ), reducing the datastore size ( using part of the original dataset to regenerate datastore), or switching a GPU with large memory

**Comment by zhengxxn** [comment]
No activity, closing.
